[package]
name = "ani-automation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ani-domain = { path = "../ani-domain" }
ani-repository = { path = "../ani-repository" }
ani-sources = { path = "../ani-sources" }
async-trait = "0.1"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
chrono-tz = "0.10"
futures-util = "0.3"
log = "0.4"
serde_json.workspace = true

[dev-dependencies]
tokio = { version = "1", features = ["io-util", "macros", "net", "rt-multi-thread"] }
