source "https://cdn.cocoapods.org/"

platform :ios, "16.0"

project "AniTracker.xcodeproj"

target "AniTracker" do
  use_frameworks! :linkage => :dynamic
  pod "MobileVLCKit", "= 3.7.3"
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "16.0"
    end
  end
end
