[package]
name = "ani-downloads"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ani-domain = { path = "../ani-domain" }
ani-repository = { path = "../ani-repository" }
async-trait = "0.1"
log = "0.4"
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
